app = "animal-crossing-id-game"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  NODE_ENV = "production"

[deploy]
  strategy = "immediate"

[[http_service]]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  
  [[http_service.ports]]
    port = 80
    handlers = ["http"]
  
  [[http_service.ports]]
    port = 443
    handlers = ["http", "tls"]
  
  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
