# Application name (must be unique across Fly.io)
app = "animal-crossing-id-game"

# Primary region for deployment
primary_region = "dfw"  # Dallas, US

[build]
  # Use the Dockerfile in the root directory
  dockerfile = "Dockerfile"

# Basic HTTP service configuration
[[http_service]]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  
  # Simple health check
  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
