[build]
builder = "NIXPACKS"
buildCommand = "npm run railway:clean && npm ci --omit=dev --no-fund --no-audit"

[deploy]
startCommand = "node src/app.js"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
